version: '2'
services:
  redis:
    image: stingar/redis:1.8
  mongodb:
    image: stingar/mongodb:1.8
  hpfeeds-cif:
    build:
      context: .
    image: hpfeeds-cif:ubuntu
    env_file:
      - hpfeeds-cif.env
    links:
      - redis
