version: '3'
services:
  redis:
    image: redis:alpine
  mongodb:
    image: mongo:3.4.24-xenial
  hpfeeds-cif:
    build:
      context: .
    image: hpfeeds-cif:ubuntu
    env_file:
      - hpfeeds-cif.env
    links:
      - redis:redis
      - mongodb:mongodb
