---
  pkgs:
    - gcc
    - git
    - mongodb

  pip_executable: pip2

  hpfeeds_cif_logdir: /var/log/hpfeeds_cif

  hpfeeds_cif_dir: /opt

  hpfeeds_repo: https://github.com/breakfastdub/hpfeeds.git
  ### NEED TO UPDATE THIS TO MASTER
  ### ONCE MASTER HAS THE FORK MERGED
  hpfeeds_version: staging
  hpfeeds_dir: /srv